### ISSUE TITLE
Document OpenTracing configuration

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-docs#100]
We've recently added OpenTracing support. We need to add documentation to describe:
- what is OpenTracing and what it does (briefly)
- how to configure it in Saleor
- example of how to use it with [Jaeger](https://www.jaegertracing.io/)

**Comment by krzysztofwolski** [comment]
@maarcingebala https://docs.saleor.io/docs/3.0/developer/running-saleor/monitoring#jaeger
Does this page needs improvement?

**Comment by maarcingebala** [comment]
The part about Jaeger looks up to date.
