### ISSUE TITLE
Warning about saleor not storing the currencies is outdated

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-docs#109]
The documentation says the following:
> The currency is not stored in the database. Changing the default currency in a production environment will not recalculate any existing orders. All numbers will remain the same and will be incorrectly displayed under the new currency.

Which is not true anymore. We should decide what to say instead. We don't support multiple currencies at the moment, but we do store them for future handling of multicurrency.

**Comment by krzysztofwolski** [comment]
Handling multicurrency is now in Channels docs (and we have separate section for prices too)
