### ISSUE TITLE
404 Page styles are broken

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor-docs#11]
![Screenshot 2019-08-08 at 19 25 12](https://user-images.githubusercontent.com/5188636/62723994-43222680-ba12-11e9-8c67-fc5dde19264e.png)

**Comment by rafalp** [comment]
Note, we have fixed `404.html` that looks properly (see #8) so this may be caching issue on our CDN.

**Comment by NyanKiyoshi** [comment]
It works now.
