### ISSUE TITLE
npm run build-assets

### ISSUE THREAD

**Issue by toppylawz** [mirumee/saleor-docs#123]
### What I'm trying to achieve
Following the standard documentation to install saleor on windows (https://docs.saleor.io/docs/getting-started/installation-windows/). On reaching step 9, I ran into the problem of 

```
npm ERR! missing script: build-assets
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     build-schema
npm ERR!     build-emails

npm ERR! A complete log of this run can be found in:
```
Please how can I fix this error? 

**System information**
Operating system: Windows 10

**Comment by maarcingebala** [comment]
@toppylawz @JAAulde We updated the docs and here is the link to the newest version of the installation guide for Windows: https://docs.saleor.io/docs/developer/installation/windows/.
The link provided by @toppylawz was referring to Saleor 2.9 where the `build-assets` command was available.

**Comment by xsKaisx** [comment]
npm run build-assets
npm ERR! Missing script: "build-assets"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
I got this on Mac? is it availble on mac yet?
