### ISSUE TITLE
Sticky topbar is hidding a few pixels of content on mobile

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-docs#15]
[![Screenshot](https://cdn.discordapp.com/attachments/356459912844541953/613606123844665397/Screenshot_20190821-073036.png)](https://cdn.discordapp.com/attachments/356459912844541953/613606123844665397/Screenshot_20190821-073036.png)

Browser: Firefox Focus
OS: Android

**Comment by krzysztofwolski** [comment]
Upgrade to Docusaurus resolved the issue.
