### ISSUE TITLE
Sidebar links don't work on mobile

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-docs#16]
1. Open the sidebar
1. Click a link, e.g. "Customizing Saleor"
1. Close the sidebar
1. The page is still the home page

[![Screenshot](https://media.discordapp.net/attachments/356459912844541953/613606123844665399/Screenshot_20190821-073051.png?width=604&height=1074)](https://media.discordapp.net/attachments/356459912844541953/613606123844665399/Screenshot_20190821-073051.png?width=604&height=1074)

Browser: Firefox Focus
OS: Android

**Comment by krzysztofwolski** [comment]
Upgrade to Docusaurus resolved the issue.
