### ISSUE TITLE
Add the two possible ways to set an environment variable on the Windows installation guide

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-docs#17]
I noticed a few times users getting confused about `$env:SECRET_KEY = "<mysecretkey>"` not working because they were using `cmd.exe` instead of powershell.

We could add a note that they need to use powershell but as it's the only part of the installation process that actually requires setting an environment variable, it would probably be best to simply include both ways:

```shell
$env:SECRET_KEY = "<mysecretkey>"

SET "SECRET_KEY=something"
```

The second is also useful for users wanting to create batch scripts (instead of powershell scripts) to run saleor or to run some saleor task/commands.

**Comment by krzysztofwolski** [comment]
Both ways are listed in the docs. Closing.
