### ISSUE TITLE
[Question] How to add Access control option to docs?

### ISSUE THREAD

**Issue by inix** [mirumee/saleor-docs#203]
Dear developers:
I want to integrate docs site into saleor that I can control which user can visit what pages.
How to config saleor to accomplish this goal?

Thanks

**Comment by patrys** [comment]
Not sure I understand the question.

**Comment by inix** [comment]
> Not sure I understand the question.

I mean that I need those doc pages such as https://docs.saleor.io/ only visible to registered users.

**Comment by patrys** [comment]
I don't think we can help as it's not something we intend to support. If you have questions about writing your own documentation, please contact the Docusaurus team, as Saleor uses Docusaurus to build and deploy its documentation.

**Comment by inix** [comment]
> I don't think we can help as it's not something we intend to support. If you have questions about writing your own documentation, please contact the Docusaurus team, as Saleor uses Docusaurus to build and deploy its documentation.

Thanks
