### ISSUE TITLE
Automatically detect invalid relative links before merging

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-docs#26]
Docusaurus displays warnings if there are dead links found by build. We should check it out, and see if it handles all kind of relative links.

It would be very easy to generate dead links over the time as we are doing implicit references unlike reST that would raise an error. And we might miss an invalid link in PR review, e.g. `.md`, `docs/blah`, ...

It could be really good to have a travis check for that or any other CI.

**Comment by krzysztofwolski** [comment]
Testing the build is now a part of CI.
