### ISSUE TITLE
Correct the spelling error in General Information card

### ISSUE THREAD

**Issue by MonikaMrozek** [mirumee/saleor-docs#41]
Correct the spelling error: General Information**s** card throughout the interface.
This should read: Information

![image](https://user-images.githubusercontent.com/53564363/65129726-3246d680-d9fc-11e9-99b7-701e13b6939a.png)

**Comment by dylmye** [comment]
Looks like it's fixed? https://github.com/mirumee/saleor-docs/blob/master/docs/dashboard/configuration/products.md
