### ISSUE TITLE
Warning blockquote background could be different from note blockquote

### ISSUE THREAD

**Issue by mateuszkula** [mirumee/saleor-docs#6]
Warning blockquote could be more emphesized so it differs from note:

So for ex. on following screenshot background for warning blockquote could be red/sth different than note background :) 🎨 
![Zrzut ekranu 2019-08-8 o 13 54 13](https://user-images.githubusercontent.com/30259869/62701258-1d7e2880-b9e4-11e9-957e-ac6881be405f.png)

**Comment by NyanKiyoshi** [comment]
I would think the note should be blue.

**Comment by krzysztofwolski** [comment]
Resolved
