### ISSUE TITLE
Broken links in Docs

### ISSUE THREAD

**Issue by parammittal16** [mirumee/saleor-docs#74]
There are some broken links in docs in intro.md file.
I want to correct them and work on this issue as of Hackoberfest.

**Comment by maarcingebala** [comment]
Which links are broken?

**Comment by traubisoda** [comment]
There is a broken link [here](https://docs.saleor.io/docs/dashboard/configuration/plugins) refering the [Extensions page](https://docs.saleor.io/docs/dashboard/configuration/advanced/extensions.md)
