### ISSUE TITLE
Fix og:url property

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-docs#85]
Curently we have the default Docuzaurus value here - https://github.com/mirumee/saleor-docs/blob/db92220dabdd18fc51f2ca31f153aaa18d84cb99/website/siteConfig.js#L16. Should be changed to `http://docs.getsaleor.com/`.

**Comment by dylmye** [comment]
Fixed by https://github.com/mirumee/saleor-docs/commit/bf258622f6445e037f7243cb648bff4eb9392d8c#diff-c272134cac3612b41f93893bbaa34d24 @mirekm - good to close?

**Comment by NyanKiyoshi** [comment]
All good now! Thanks @dylmye for noticing!
