### ISSUE TITLE
Installation steps Prepare front-end assets command doesn't exist

### ISSUE THREAD

**Issue by FabioRosado** [mirumee/saleor-docs#91]
Hello everyone,
I was following the steps on the installation guide and when I try to run the command `npm run build-assets`  it seems this command doesn't exist anymore. This is what npm throws back at me:

```
npm ERR! missing script: build-assets
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     build-schema
npm ERR!     build-emails
```
I think the build-assets was renamed to build-schema? I'm happy to raise a PR that fixes the docs if this is the case.

Thank you for reading 👍

**Comment by NyanKiyoshi** [comment]
Hi! On master the command `build-assets` was removed as we have dropped the storefront 1.0; but it wasn't released yet.

**Comment by FabioRosado** [comment]
That makes sense, should I go ahead and update the docs then? 🤔

**Comment by NyanKiyoshi** [comment]
Well it is an open-source project so you can fell free to open a pull request for it! But in #89 we will also need to add steps about how to install the storefront and dashboard 2.0 which is another step. Removing the non-longer valid step is definitively a good start 👍
