### ISSUE TITLE
Document JWT configurations such as expirations and refreshes

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-docs#96]
It would be important for user to know how the JWT flow works and how to customize it. Refering to https://django-graphql-jwt.domake.io/en/latest/settings.html#token-expiration we could include information, guidelines and defaults for `JWT_VERIFY_EXPIRATION`, `JWT_EXPIRATION_DELTA`, `JWT_ALLOW_REFRESH`, `JWT_REFRESH_EXPIRATION_DELTA` and `JWT_LONG_RUNNING_REFRESH_TOKEN`.

**Comment by krzysztofwolski** [comment]
JWT configuration added in #134
