### ISSUE TITLE
Document usage of GraphQL API with Service Account's `auth_token`

### ISSUE THREAD

**Issue by derenio** [mirumee/saleor-docs#97]
We should document:
1. Usage of the `Authorization: Bearer _auth_token_` header as a method of authorization (https://github.com/mirumee/saleor-docs/blob/master/docs/api/authenticate.md),
2. The webhooks' registration process done through the GraphQL's API with the _auth_token_ in addition to the registration done through the dashboard.

**Comment by krzysztofwolski** [comment]
Added https://docs.saleor.io/docs/next/developer/extending/apps
